"""add libraries and library_entries

Revision ID: 660209896770
Revises: b1_phase6_content_only_authoring
Create Date: 2026-08-26 16:50:28.184579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '660209896770'
down_revision: Union[str, None] = 'b1_phase6_content_only_authoring'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libraries_user_id'), 'libraries', ['user_id'], unique=True)
    op.create_table('library_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('library_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_library_entries_library_id'), 'library_entries', ['library_id'], unique=False)
    op.create_index('ix_library_entries_library_kind', 'library_entries', ['library_id', 'kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_library_entries_library_kind', table_name='library_entries')
    op.drop_index(op.f('ix_library_entries_library_id'), table_name='library_entries')
    op.drop_table('library_entries')
    op.drop_index(op.f('ix_libraries_user_id'), table_name='libraries')
    op.drop_table('libraries')
    # ### end Alembic commands ###
