/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedWorkspaceRouteRouteImport } from './routes/_authenticated/_workspace/route'
import { Route as AuthenticatedBuilderRouteRouteImport } from './routes/_authenticated/builder/route'
import { Route as AuthenticatedWorkspaceApplicationsRouteRouteImport } from './routes/_authenticated/_workspace/applications/route'
import { Route as AuthenticatedWorkspaceCvsRouteImport } from './routes/_authenticated/_workspace/cvs'
import { Route as AuthenticatedWorkspaceDashboardRouteImport } from './routes/_authenticated/_workspace/dashboard'
import { Route as AuthenticatedWorkspaceLibraryRouteImport } from './routes/_authenticated/_workspace/library'
import { Route as AuthenticatedWorkspaceSettingsRouteImport } from './routes/_authenticated/_workspace/settings'
import { Route as AuthenticatedBuilderIdRouteImport } from './routes/_authenticated/builder/$id'
import { Route as AgentTailorSessionIdRouteImport } from './routes/agent/tailor/$sessionId'
import { Route as AuthenticatedWorkspaceApplicationsIdRouteImport } from './routes/_authenticated/_workspace/applications/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceRouteRoute =
  AuthenticatedWorkspaceRouteRouteImport.update({
    id: '/_workspace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuilderRouteRoute =
  AuthenticatedBuilderRouteRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceApplicationsRouteRoute =
  AuthenticatedWorkspaceApplicationsRouteRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedWorkspaceRouteRoute,
  } as any)
const AuthenticatedWorkspaceCvsRoute =
  AuthenticatedWorkspaceCvsRouteImport.update({
    id: '/cvs',
    path: '/cvs',
    getParentRoute: () => AuthenticatedWorkspaceRouteRoute,
  } as any)
const AuthenticatedWorkspaceDashboardRoute =
  AuthenticatedWorkspaceDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedWorkspaceRouteRoute,
  } as any)
const AuthenticatedWorkspaceLibraryRoute =
  AuthenticatedWorkspaceLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedWorkspaceRouteRoute,
  } as any)
const AuthenticatedWorkspaceSettingsRoute =
  AuthenticatedWorkspaceSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWorkspaceRouteRoute,
  } as any)
const AuthenticatedBuilderIdRoute = AuthenticatedBuilderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBuilderRouteRoute,
} as any)
const AgentTailorSessionIdRoute = AgentTailorSessionIdRouteImport.update({
  id: '/agent/tailor/$sessionId',
  path: '/agent/tailor/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceApplicationsIdRoute =
  AuthenticatedWorkspaceApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedWorkspaceApplicationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/builder': typeof AuthenticatedBuilderRouteRouteWithChildren
  '/applications': typeof AuthenticatedWorkspaceApplicationsRouteRouteWithChildren
  '/cvs': typeof AuthenticatedWorkspaceCvsRoute
  '/dashboard': typeof AuthenticatedWorkspaceDashboardRoute
  '/library': typeof AuthenticatedWorkspaceLibraryRoute
  '/settings': typeof AuthenticatedWorkspaceSettingsRoute
  '/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/agent/tailor/$sessionId': typeof AgentTailorSessionIdRoute
  '/applications/$id': typeof AuthenticatedWorkspaceApplicationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/builder': typeof AuthenticatedBuilderRouteRouteWithChildren
  '/applications': typeof AuthenticatedWorkspaceApplicationsRouteRouteWithChildren
  '/cvs': typeof AuthenticatedWorkspaceCvsRoute
  '/dashboard': typeof AuthenticatedWorkspaceDashboardRoute
  '/library': typeof AuthenticatedWorkspaceLibraryRoute
  '/settings': typeof AuthenticatedWorkspaceSettingsRoute
  '/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/agent/tailor/$sessionId': typeof AgentTailorSessionIdRoute
  '/applications/$id': typeof AuthenticatedWorkspaceApplicationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/_workspace': typeof AuthenticatedWorkspaceRouteRouteWithChildren
  '/_authenticated/builder': typeof AuthenticatedBuilderRouteRouteWithChildren
  '/_authenticated/_workspace/applications': typeof AuthenticatedWorkspaceApplicationsRouteRouteWithChildren
  '/_authenticated/_workspace/cvs': typeof AuthenticatedWorkspaceCvsRoute
  '/_authenticated/_workspace/dashboard': typeof AuthenticatedWorkspaceDashboardRoute
  '/_authenticated/_workspace/library': typeof AuthenticatedWorkspaceLibraryRoute
  '/_authenticated/_workspace/settings': typeof AuthenticatedWorkspaceSettingsRoute
  '/_authenticated/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/agent/tailor/$sessionId': typeof AgentTailorSessionIdRoute
  '/_authenticated/_workspace/applications/$id': typeof AuthenticatedWorkspaceApplicationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/builder'
    | '/applications'
    | '/cvs'
    | '/dashboard'
    | '/library'
    | '/settings'
    | '/builder/$id'
    | '/agent/tailor/$sessionId'
    | '/applications/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/builder'
    | '/applications'
    | '/cvs'
    | '/dashboard'
    | '/library'
    | '/settings'
    | '/builder/$id'
    | '/agent/tailor/$sessionId'
    | '/applications/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/_workspace'
    | '/_authenticated/builder'
    | '/_authenticated/_workspace/applications'
    | '/_authenticated/_workspace/cvs'
    | '/_authenticated/_workspace/dashboard'
    | '/_authenticated/_workspace/library'
    | '/_authenticated/_workspace/settings'
    | '/_authenticated/builder/$id'
    | '/agent/tailor/$sessionId'
    | '/_authenticated/_workspace/applications/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AgentTailorSessionIdRoute: typeof AgentTailorSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_workspace': {
      id: '/_authenticated/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_workspace/applications': {
      id: '/_authenticated/_workspace/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedWorkspaceApplicationsRouteRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRouteRoute
    }
    '/_authenticated/_workspace/cvs': {
      id: '/_authenticated/_workspace/cvs'
      path: '/cvs'
      fullPath: '/cvs'
      preLoaderRoute: typeof AuthenticatedWorkspaceCvsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRouteRoute
    }
    '/_authenticated/_workspace/dashboard': {
      id: '/_authenticated/_workspace/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedWorkspaceDashboardRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRouteRoute
    }
    '/_authenticated/_workspace/library': {
      id: '/_authenticated/_workspace/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedWorkspaceLibraryRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRouteRoute
    }
    '/_authenticated/_workspace/settings': {
      id: '/_authenticated/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedWorkspaceSettingsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRouteRoute
    }
    '/_authenticated/builder/$id': {
      id: '/_authenticated/builder/$id'
      path: '/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof AuthenticatedBuilderIdRouteImport
      parentRoute: typeof AuthenticatedBuilderRouteRoute
    }
    '/agent/tailor/$sessionId': {
      id: '/agent/tailor/$sessionId'
      path: '/agent/tailor/$sessionId'
      fullPath: '/agent/tailor/$sessionId'
      preLoaderRoute: typeof AgentTailorSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_workspace/applications/$id': {
      id: '/_authenticated/_workspace/applications/$id'
      path: '/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof AuthenticatedWorkspaceApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedWorkspaceApplicationsRouteRoute
    }
  }
}

interface AuthenticatedWorkspaceApplicationsRouteRouteChildren {
  AuthenticatedWorkspaceApplicationsIdRoute: typeof AuthenticatedWorkspaceApplicationsIdRoute
}

const AuthenticatedWorkspaceApplicationsRouteRouteChildren: AuthenticatedWorkspaceApplicationsRouteRouteChildren =
  {
    AuthenticatedWorkspaceApplicationsIdRoute:
      AuthenticatedWorkspaceApplicationsIdRoute,
  }

const AuthenticatedWorkspaceApplicationsRouteRouteWithChildren =
  AuthenticatedWorkspaceApplicationsRouteRoute._addFileChildren(
    AuthenticatedWorkspaceApplicationsRouteRouteChildren,
  )

interface AuthenticatedWorkspaceRouteRouteChildren {
  AuthenticatedWorkspaceApplicationsRouteRoute: typeof AuthenticatedWorkspaceApplicationsRouteRouteWithChildren
  AuthenticatedWorkspaceCvsRoute: typeof AuthenticatedWorkspaceCvsRoute
  AuthenticatedWorkspaceDashboardRoute: typeof AuthenticatedWorkspaceDashboardRoute
  AuthenticatedWorkspaceLibraryRoute: typeof AuthenticatedWorkspaceLibraryRoute
  AuthenticatedWorkspaceSettingsRoute: typeof AuthenticatedWorkspaceSettingsRoute
}

const AuthenticatedWorkspaceRouteRouteChildren: AuthenticatedWorkspaceRouteRouteChildren =
  {
    AuthenticatedWorkspaceApplicationsRouteRoute:
      AuthenticatedWorkspaceApplicationsRouteRouteWithChildren,
    AuthenticatedWorkspaceCvsRoute: AuthenticatedWorkspaceCvsRoute,
    AuthenticatedWorkspaceDashboardRoute: AuthenticatedWorkspaceDashboardRoute,
    AuthenticatedWorkspaceLibraryRoute: AuthenticatedWorkspaceLibraryRoute,
    AuthenticatedWorkspaceSettingsRoute: AuthenticatedWorkspaceSettingsRoute,
  }

const AuthenticatedWorkspaceRouteRouteWithChildren =
  AuthenticatedWorkspaceRouteRoute._addFileChildren(
    AuthenticatedWorkspaceRouteRouteChildren,
  )

interface AuthenticatedBuilderRouteRouteChildren {
  AuthenticatedBuilderIdRoute: typeof AuthenticatedBuilderIdRoute
}

const AuthenticatedBuilderRouteRouteChildren: AuthenticatedBuilderRouteRouteChildren =
  {
    AuthenticatedBuilderIdRoute: AuthenticatedBuilderIdRoute,
  }

const AuthenticatedBuilderRouteRouteWithChildren =
  AuthenticatedBuilderRouteRoute._addFileChildren(
    AuthenticatedBuilderRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWorkspaceRouteRoute: typeof AuthenticatedWorkspaceRouteRouteWithChildren
  AuthenticatedBuilderRouteRoute: typeof AuthenticatedBuilderRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWorkspaceRouteRoute:
    AuthenticatedWorkspaceRouteRouteWithChildren,
  AuthenticatedBuilderRouteRoute: AuthenticatedBuilderRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AgentTailorSessionIdRoute: AgentTailorSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
