/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedBuilderRouteRouteImport } from './routes/_authenticated/builder/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedBuilderIdRouteImport } from './routes/_authenticated/builder/$id'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardApplicationsRouteRouteImport } from './routes/_authenticated/dashboard/applications/route'
import { Route as AuthenticatedDashboardCvsRouteImport } from './routes/_authenticated/dashboard/cvs'
import { Route as AuthenticatedDashboardLibraryRouteImport } from './routes/_authenticated/dashboard/library'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AgentTailorSessionIdRouteImport } from './routes/agent/tailor/$sessionId'
import { Route as AuthenticatedDashboardApplicationsIdRouteImport } from './routes/_authenticated/dashboard/applications/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBuilderRouteRoute =
  AuthenticatedBuilderRouteRouteImport.update({
    id: '/builder',
    path: '/builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuilderIdRoute = AuthenticatedBuilderIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBuilderRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardApplicationsRouteRoute =
  AuthenticatedDashboardApplicationsRouteRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardCvsRoute =
  AuthenticatedDashboardCvsRouteImport.update({
    id: '/cvs',
    path: '/cvs',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardLibraryRoute =
  AuthenticatedDashboardLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const AgentTailorSessionIdRoute = AgentTailorSessionIdRouteImport.update({
  id: '/agent/tailor/$sessionId',
  path: '/agent/tailor/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardApplicationsIdRoute =
  AuthenticatedDashboardApplicationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardApplicationsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/builder': typeof AuthenticatedBuilderRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/dashboard/applications': typeof AuthenticatedDashboardApplicationsRouteRouteWithChildren
  '/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/dashboard/cvs': typeof AuthenticatedDashboardCvsRoute
  '/dashboard/library': typeof AuthenticatedDashboardLibraryRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/agent/tailor/$sessionId': typeof AgentTailorSessionIdRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/applications/$id': typeof AuthenticatedDashboardApplicationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/builder': typeof AuthenticatedBuilderRouteRouteWithChildren
  '/dashboard/applications': typeof AuthenticatedDashboardApplicationsRouteRouteWithChildren
  '/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/dashboard/cvs': typeof AuthenticatedDashboardCvsRoute
  '/dashboard/library': typeof AuthenticatedDashboardLibraryRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/agent/tailor/$sessionId': typeof AgentTailorSessionIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/applications/$id': typeof AuthenticatedDashboardApplicationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/builder': typeof AuthenticatedBuilderRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_authenticated/dashboard/applications': typeof AuthenticatedDashboardApplicationsRouteRouteWithChildren
  '/_authenticated/builder/$id': typeof AuthenticatedBuilderIdRoute
  '/_authenticated/dashboard/cvs': typeof AuthenticatedDashboardCvsRoute
  '/_authenticated/dashboard/library': typeof AuthenticatedDashboardLibraryRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/agent/tailor/$sessionId': typeof AgentTailorSessionIdRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/applications/$id': typeof AuthenticatedDashboardApplicationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/builder'
    | '/dashboard'
    | '/dashboard/applications'
    | '/builder/$id'
    | '/dashboard/cvs'
    | '/dashboard/library'
    | '/dashboard/settings'
    | '/agent/tailor/$sessionId'
    | '/dashboard/'
    | '/dashboard/applications/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/builder'
    | '/dashboard/applications'
    | '/builder/$id'
    | '/dashboard/cvs'
    | '/dashboard/library'
    | '/dashboard/settings'
    | '/agent/tailor/$sessionId'
    | '/dashboard'
    | '/dashboard/applications/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/builder'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/applications'
    | '/_authenticated/builder/$id'
    | '/_authenticated/dashboard/cvs'
    | '/_authenticated/dashboard/library'
    | '/_authenticated/dashboard/settings'
    | '/agent/tailor/$sessionId'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/applications/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AgentTailorSessionIdRoute: typeof AgentTailorSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/builder': {
      id: '/_authenticated/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthenticatedBuilderRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/builder/$id': {
      id: '/_authenticated/builder/$id'
      path: '/$id'
      fullPath: '/builder/$id'
      preLoaderRoute: typeof AuthenticatedBuilderIdRouteImport
      parentRoute: typeof AuthenticatedBuilderRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/applications': {
      id: '/_authenticated/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof AuthenticatedDashboardApplicationsRouteRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/cvs': {
      id: '/_authenticated/dashboard/cvs'
      path: '/cvs'
      fullPath: '/dashboard/cvs'
      preLoaderRoute: typeof AuthenticatedDashboardCvsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/library': {
      id: '/_authenticated/dashboard/library'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof AuthenticatedDashboardLibraryRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/agent/tailor/$sessionId': {
      id: '/agent/tailor/$sessionId'
      path: '/agent/tailor/$sessionId'
      fullPath: '/agent/tailor/$sessionId'
      preLoaderRoute: typeof AgentTailorSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/applications/$id': {
      id: '/_authenticated/dashboard/applications/$id'
      path: '/$id'
      fullPath: '/dashboard/applications/$id'
      preLoaderRoute: typeof AuthenticatedDashboardApplicationsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardApplicationsRouteRoute
    }
  }
}

interface AuthenticatedBuilderRouteRouteChildren {
  AuthenticatedBuilderIdRoute: typeof AuthenticatedBuilderIdRoute
}

const AuthenticatedBuilderRouteRouteChildren: AuthenticatedBuilderRouteRouteChildren =
  {
    AuthenticatedBuilderIdRoute: AuthenticatedBuilderIdRoute,
  }

const AuthenticatedBuilderRouteRouteWithChildren =
  AuthenticatedBuilderRouteRoute._addFileChildren(
    AuthenticatedBuilderRouteRouteChildren,
  )

interface AuthenticatedDashboardApplicationsRouteRouteChildren {
  AuthenticatedDashboardApplicationsIdRoute: typeof AuthenticatedDashboardApplicationsIdRoute
}

const AuthenticatedDashboardApplicationsRouteRouteChildren: AuthenticatedDashboardApplicationsRouteRouteChildren =
  {
    AuthenticatedDashboardApplicationsIdRoute:
      AuthenticatedDashboardApplicationsIdRoute,
  }

const AuthenticatedDashboardApplicationsRouteRouteWithChildren =
  AuthenticatedDashboardApplicationsRouteRoute._addFileChildren(
    AuthenticatedDashboardApplicationsRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardApplicationsRouteRoute: typeof AuthenticatedDashboardApplicationsRouteRouteWithChildren
  AuthenticatedDashboardCvsRoute: typeof AuthenticatedDashboardCvsRoute
  AuthenticatedDashboardLibraryRoute: typeof AuthenticatedDashboardLibraryRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardApplicationsRouteRoute:
      AuthenticatedDashboardApplicationsRouteRouteWithChildren,
    AuthenticatedDashboardCvsRoute: AuthenticatedDashboardCvsRoute,
    AuthenticatedDashboardLibraryRoute: AuthenticatedDashboardLibraryRoute,
    AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuilderRouteRoute: typeof AuthenticatedBuilderRouteRouteWithChildren
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuilderRouteRoute: AuthenticatedBuilderRouteRouteWithChildren,
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AgentTailorSessionIdRoute: AgentTailorSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
